### ISSUE TITLE
UUID Timestamp reported as Mar 1983?

### ISSUE THREAD

**Issue by RedSpid3r** [LiosK/uuidv7#11]
I generated UUID `018e3f04-0218-7f62-8f86-6a3cfe5a42fb` on `2024-03-14 22:02:48` however, when using the validator on https://uuid7.com/ it reports: `UUIDv7 is valid with time: Sun, 27 Mar 1983 05:36:00 GMT`

![image](https://github.com/LiosK/uuidv7/assets/12657277/78e3bbba-d543-4601-8d1b-71e0d835d28c)

Is this a problem with this lib or a problem with uuidv7.com ?

**Comment by LiosK** [comment]
uuidv7.com seems to be broken. The leading 018e3f04-0218 indicates the millisecond Unix timestamp in hex and it points to the year 2024. uuidv7.com shows a wrong date too for the example UUIDv7 provided in the draft RFC.

**Comment by RedSpid3r** [comment]
Thanks for confirming. Will close this out :)

**Comment by RzNmKX** [comment]
> uuidv7.com seems to be broken. The leading 018e3f04-0218 indicates the millisecond Unix timestamp in hex and it points to the year 2024. uuidv7.com shows a wrong date too for the example UUIDv7 provided in the draft RFC.

I have adjusted to use the latest draft, the 018 example now correctly shows 2024.

https://github.com/RzNmKX/uuid7-flask/commit/93edde9e98248423dbf2ce6ae05a220551836218

**Comment by RzNmKX** [comment]
> I generated UUID `018e3f04-0218-7f62-8f86-6a3cfe5a42fb` on `2024-03-14 22:02:48` however, when using the validator on https://uuid7.com/ it reports: `UUIDv7 is valid with time: Sun, 27 Mar 1983 05:36:00 GMT`
> 
> ![image](https://private-user-images.githubusercontent.com/12657277/313015865-78e3bbba-d543-4601-8d1b-71e0d835d28c.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA5OTMyODAsIm5iZiI6MTcxMDk5Mjk4MCwicGF0aCI6Ii8xMjY1NzI3Ny8zMTMwMTU4NjUtNzhlM2JiYmEtZDU0My00NjAxLThkMWItNzFlMGQ4MzVkMjhjLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMjElMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzIxVDAzNDk0MFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTA2NDZiNTMxMTAzNzJmMWVjZDQ1OWY1ZTk2MTEwMDc5OTAwNGQ0NjQ0MGIwMDM5OGUwNDAxNzA3ZmJlODgyYTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.XIlD4E89l6p1zMOaGpqxodF3mhbdse-yRbJuyxrkHvM)
> 
> Is this a problem with this lib or a problem with uuidv7.com ?

This is now changed on https://uuid7.com - adjusted to use the latest draft: https://github.com/RzNmKX/uuid7-flask/commit/93edde9e98248423dbf2ce6ae05a220551836218

your example `018e3f04-0218-7f62-8f86-6a3cfe5a42fb` now returns `Thu, 14 Mar 2024 22:10:11 GMT`. Are you sure you didn't do it at 22:10:11?

**Comment by RedSpid3r** [comment]
> your example `018e3f04-0218-7f62-8f86-6a3cfe5a42fb` now returns `Thu, 14 Mar 2024 22:10:11 GMT`. Are you sure you didn't do it at 22:10:11?

I guess it's possible I re-used that ID when i was testing. I just check the last entered ID in my db `018e791c-e8f6-7725-b5b8-7e8aa279cf4c` and this is correctly showing as `Tue, 26 Mar 2024 04:55:21 GMT` on [UUIDv7.com](https://uuid7.com) so it looks like everything is working as intended now 😄 

![image](https://github.com/LiosK/uuidv7/assets/12657277/dedc5130-d8ff-4434-b25d-99ff2ab1ad5d)
