### ISSUE TITLE
Export CommonJS in addition to ES Modules

### ISSUE THREAD

**Issue by leite08** [LiosK/uuidv7#4]
Currently this project exports ESM packages on NPM. It would be useful to have CJS exported as well for projects that rely on that format.

### Our Use Case

In our setup, we transpile our Typescript code into CJS. After installing `uuidv7` from NPM the transpilation works fine (`tsc`), but we couldn't make our Jest to work.

We get `SyntaxError: Unexpected token 'export'` because out setup is for CJS, but the imported source from `uuidv7` is ESM.

<img width="1242" alt="image" src="https://github.com/LiosK/uuidv7/assets/2132564/c01c5120-1245-4c49-b52b-f9d8c9312d78">

If we take the route to adjust our setup to ESM [[1](https://stackoverflow.com/a/75001235/2099911), [2](https://kulshekhar.github.io/ts-jest/docs/guides/esm-support/)] this goes away, but a bunch of other stuff break.

### Proposed Solution

1. Create separate `tsconfig` files, one for CJS and another for ESM;
1. Update the `build` script to transpile twice, once for each `tsconfig`;
2. Update `package.json` to export `imports` to the ESM `dist` folder and `requires` to the CJS `dist` folder.

Source: https://www.sensedeep.com/blog/posts/2021/how-to-create-single-source-npm-module.html

**Comment by LiosK** [comment]
Thank you for the request. The age of dual packaging seems to be over, and many libraries are migrating to the pure ESM arrangement. I'm currently not planning to reintroduce a CJS entry point.

**Comment by leite08** [comment]
Thanks for the response and for building this!

**Comment by reecefenwick** [comment]
Hitting this issue as well. @leite08 would you mind sharing the approach you ended up taking, if any?

It would be great if you could re-consider supporting CJS as well @LiosK, I don't think the ecosystem is there yet in terms of ESM support and this could inhibit adoption of your awesome library

**Comment by LiosK** [comment]
Let's see if other similar requests will come.

**Comment by leite08** [comment]
@reecefenwick we just ended up copying the [index.ts file](https://github.com/LiosK/uuidv7/blob/main/src/index.ts).

Other attempts (mainly make our project ESM-only) led to other libraries CJS-only to break.

**Comment by reecefenwick** [comment]
I ended up using https://github.com/jetpack-io/typeid-js as it was more of a complete solution for what I was doing, but it uses this library under the hood so thanks for your work @LiosK !

**Comment by bakura10** [comment]
I'm also facing this issue. I also ended up copying the file locally, but it makes upgrades harder :). Would love it to be exported as CommonJS as well.

**Comment by LiosK** [comment]
[v0.6](https://github.com/LiosK/uuidv7/releases/tag/v0.6.0) reintroduced the CommonJS entry point! However, I will remove it once this library reaches the stable release (v1.0). I am planning to make the last unstable release (v0.x) functionally equivalent to v1.0 except the CommonJS export, so that those who want the CJS support can stay with that unstable release, but no new feature will be offered to CJS users.
