### ISSUE TITLE
How experimental is this library?

### ISSUE THREAD

**Issue by benjick** [LiosK/uuidv7#6]
Hey!

I'm interested in using uuidv7 in my postgres database, but my cloud provider does not support it so I'm thinking I can generate them in the app layer. This library was the first hit but the readme mentions experimental, how experimental is it? Can I use it in production?

Cheers

**Comment by LiosK** [comment]
Hi! It's almost stable, and I'm planning to bump it to v1 as is (except [CJS support](https://github.com/LiosK/uuidv7#commonjs-support)) once the new RFC is officially released. In this sense, this library is as experimental as the draft RFC.
