### ISSUE TITLE
Why do we allow rollback at all?

### ISSUE THREAD

**Issue by rex-remind101** [LiosK/uuidv7#7]
Thank you for writing up this library. I was reading through the library and everything looks good in my eyes except these few lines seemed very confusing to me. I thought the point of uuidv7 is it's always created in monotonically increasing order based on time and when time is equal then on count. Having rollback breaks that ordering and from my understanding would then break uuidv7. Why was this added then? Should the function instead be fallible (maybe throw an error) and force the user to retry?

Thanks

https://github.com/LiosK/uuidv7/blob/f30b7a7faff73afbce0b27a46c638310f96912ba/src/index.ts#L354-L364

**Comment by rex-remind101** [comment]
cc @franleplant

**Comment by LiosK** [comment]
Hi! That's a good question. *By default*, this library rolls back on an extremely rare condition where the system clock rolls back by more than 10 seconds. This is based on an assumption that general users do not require an absolute guarantee of monotonically increasing order of generated IDs and for such users it would be painful to check errors for such a rare circumstance every time they just want a unique ID.

If you need the absolute guarantee, you can use the advanced feature, `V7Generator` and `generateOrAbort`. Please take a look at the example code in the document: https://github.com/LiosK/uuidv7/tree/f30b7a7faff73afbce0b27a46c638310f96912ba#other-features
